# Generated by Django 6.0.6 on 2026-06-24 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short description of skills and experience', max_length=1000)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate rate in NPR per hour/visit', max_digits=8, null=True)),
                ('service_area', models.CharField(blank=True, help_text='e.g. Kathmandu, Pokhara, Lalitpur', max_length=255)),
                ('citizenship_or_license', models.FileField(blank=True, help_text='Citizenship or license document for verification', null=True, upload_to='provider_documents/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='services.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
